#!/bin/bash

if [[ $# < 1 ]]; then
    echo "Usage: (echo title; cat body) | $0 sender [ action_token ] [ error ]"
    exit 1
fi

if [ -n "$3" ]; then
    echo $3 1>&2
    exit 1
fi

echo sender=$1
if [ -n "$2" ]; then
    echo action_token=$2
fi
echo

read TITLE
echo TITLE=$TITLE
echo === BODY STARTS
cat
echo === BODY ENDS
