#!/bin/bash

if [[ $# < 2 ]]; then
    echo "Usage: (echo title; cat body) | $0 action_token sender"
    exit 1
fi

echo action_token=$1
echo sender=$2

echo stderr 1>&2 # prints stderr to stderr

read TITLE
echo TITLE=$TITLE
echo === BODY STARTS
cat
echo === BODY ENDS

exit 1
