#!/bin/bash

if [[ $# < 2 ]]; then
    echo "Usage: (echo title; cat body) | $0 post_path sender"
    exit 1
fi

echo post_path=$1
echo sender=$2

echo stderr 1>&2 # prints stderr to stderr

read TITLE
echo TITLE=$TITLE
echo === BODY STARTS
cat
echo === BODY ENDS
